version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
